// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEx9aSa_-5cd7pYjx_1bakOcUw7CSRc0M',
    appId: '1:251656021155:web:0d20fbdd29550dc90b8b16',
    messagingSenderId: '251656021155',
    projectId: 'tennisapplication-f2829',
    authDomain: 'tennisapplication-f2829.firebaseapp.com',
    storageBucket: 'tennisapplication-f2829.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbxgw0RjLcM3wElTX8r-56z12sSjOuOhY',
    appId: '1:251656021155:android:fc7026bf37ba9f0e0b8b16',
    messagingSenderId: '251656021155',
    projectId: 'tennisapplication-f2829',
    storageBucket: 'tennisapplication-f2829.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASmkkqKbypNb3H8_MRFDfDqr7aQrZPzzo',
    appId: '1:251656021155:ios:01a40ccb0431ed1e0b8b16',
    messagingSenderId: '251656021155',
    projectId: 'tennisapplication-f2829',
    storageBucket: 'tennisapplication-f2829.firebasestorage.app',
    iosBundleId: 'com.example.tennisApplication',
  );
}
